id: A3FF3388E
base_file: fC420.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:16:09.382838
  last_modified_at: 2022-06-15 20:16:09.382846
